// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Study_dashboard_API.Data;

#nullable disable

namespace Study_dashboard_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Study_dashboard_API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Name = "Kuba1",
                            Password = "kuba1111"
                        },
                        new
                        {
                            UserId = 2,
                            Name = "Kuba2",
                            Password = "kuba2222"
                        },
                        new
                        {
                            UserId = 3,
                            Name = "Kuba3",
                            Password = "kuba3333"
                        },
                        new
                        {
                            UserId = 4,
                            Name = "Kuba4",
                            Password = "kuba4444"
                        },
                        new
                        {
                            UserId = 5,
                            Name = "Kuba5",
                            Password = "kuba5555"
                        },
                        new
                        {
                            UserId = 6,
                            Name = "Kuba6",
                            Password = "kuba6666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
